# Site settings
title: Infostore
email: jem@cs.umu.se
description: "Lite av varje"
baseurl: "http://jematwork.github.io/infostore"
url: "http://jematwork.github.io/infostore"

# Build settings
markdown: kramdown
permalink: pretty
